# Site settings
title: Bruno Lima - Desenvolvedor e graduando em engenharia de computação
description: "Simples blog de um desenvolvedor, estudante de engenharia de computação escrevendo sobre desenvolvimento web, software, tecnologia e afins."
baseurl: ""
autor: Bruno Lima da Silva
url: "https://bls.rocks"
email: brunolsk3@gmail.com
github: blsdotrocks
codepen: blsdotrocks
twitter: blsdotrocks

# Build settings
markdown: kramdown
permalink: /:title/
